spring:
  application:
    name: profile-service
    jackson.serialization.indent_output: true

server:
  port: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      circuitbreakers.enabled: true
      show-details: always

resilience4j.circuitbreaker:
  instances:
    getprofile:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 5
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException
        - java.net.ConnectException

resilience4j.ratelimiter:
  instances:
    getprofile:
      limitForPeriod: 10
      limitRefreshPeriod: 100000
      timeoutDuration: 1000ms

resilience4j.retry:
  instances:
    retryGetprofile:
      maxRetryAttempts: 5
      waitDuration: 10000

resilience4j.bulkhead:
  instances:
    bulkheadGetProfile:
      maxWaitDuration: 10ms
      maxConcurrentCall: 30

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/